* zo brale'ugau
lu RO DO TOLMOhI LO NU BRALEhUGAU MEhO YhYBU li'u pu selsku la .durkas. 
* zo ceirkalci
smudu'i zo solji gau la .cntr.
* zo de'a'ai
simsa lu de'a jundi li'u .i ca'e zo de'a'ai cmavo ma'oi COI .i cusku
ko'oi va'o lo nu tolrinsa pu zi ca lo nu ze'i tolju'i .i zo di'a'ai simsa
* zo de'enpa
ti'e smuni simsa lo'u ze'u denpa le'u 
.i citmle ke cusku staile ke'e valsi ti'e za'a 
* zo di'a'ai
simsa lu di'a jundi li'u .i ca'e zo di'a'ai cmavo ma'oi COI .i cusku
ko'oi va'o lo nu rinsa ba zi ca lo nu ze'i tolju'i .i zo de'a'ai simsa
* zo du'ukse
mutce dukse
* zo fai
la durkavore pu cusku zoi .glic. 
fai: [FA] place tag: rescue a sumti from the crazy escape trajectory upon which it was launched by {jai}
.glic. .u'i 
* zo fegli
tolmle
* zo glitolmo'i
to'e morji fi lo glico .i jdika lo ka gligoiselbau .i zo jbotolmo'i
simsa
ni'o mi mi'e la .selkik. cu pu pilno zo glitolmo'i lo nu tavla fi lo
nu jbotadni .i mi xalbo lo nu glitolmo'i se ja'e lo nu jbotadnytcetce
.i je'u mi no roi glitolmo'i ri'a lo nu jbotadni .i ku'i cinri xu nai sidbo
* zo .irci
basti ka'u za'a zo .irk.
.i clira nu pilno lo vlatai
.i zoi .tarmi. KZZK .tarmi. goi ko'a vlatai zo .irci
.i ca lo nu zo .irci se finti kei ko'a mutce lo ka na'e cafne se pilno 
.i pu cizra simlu fa lo nu sampu je zifre plixau pilno ko'a 
.i cizra vlipa za'a fa lo nu finti lo milxe je sampu po'u zo .irci 
   zi'e noi mutce lo ka djedi jikca plixau 
.i za'a ca lo nu zo .irci co'a zasti kei la .lojban. binxo lo fictce
* zo jai
.oi
* zo jbotolmo'i
to'e morji fi lo lojbo .i jdika lo ka jboselbau .i simsa zo glitolmo'i
* zo kuktce
la stela selckiku cu finti zo kuktce
mu'i lo nu melbi fa lo za'i zo kukte zo kuktce cu simsa 
.i rirxe simsa sance
* zo makfa
xu do morji fi lo cedra be lo nu cafne fa lo nu cusku zo makfa 
* zo mlevla
lo mlevla cu valsi lo se mlevla lo te mlevla gi'e melbi lo ve mlevla lo xe mlevla lo xe xi xa mlevla 
.i .ia zo mlevla mlevla
* zo morji
ralte lo sidbo
* zo nalxada
lu lo nu da'i x1 na fasnu cu xlali li'u selsku la solpa'i
* zo nanba
kuktce
* zo parcicize
1337
* zo pinjyglu
condom
* zo .putcid.
reddit
* zo rotflololo
la veljunpei pu finti
.i vy. cusku lu ca'e rotflololo(+): x1 gunro x2 gi'e cmila sela'u lodu'u zo lo rapli xokau bu'u lo ti valsi fanmo li'u
* zo rotpaci
k1 (grkg) vf gur ebg13-rapbqrq sbez bs k2 (grkg)
* zo vi'okte
za'a la menli cu cusku zo vi'okte .i ru'a smudu'i zo vi'o zei zukte je cu
simsa zo tinbe
* zo zabnrkulu
cool
* zo zajba
pe'i mo'a nunpli 
.i so'u roi pilno zo zajba .ui nai 
.i .ia sai ganra zmadu smuni
.i mu'a .ia pilno fi'o glico simsa zoi .gy. exercise .gy. 
.i ro nu xadni muvdu zo'u ko pilno 
.i mlegi'u pe'i 
* zo zeildeju
simsa ti'e lu ze'i de'a jundi li'u 
.i lu zi'evla .i sinxa lo du'u ze'i de'a jundi li'u se cusku la selpa'i 
